src/main/java/com/example/place/ManiaPlaceApplication.java
src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/item/entity/Item.java
src/main/java/com/example/place/domain/item/repository/ItemRepository.java
src/main/java/com/example/place/domain/item/service/ItemService.java
src/main/java/com/example/place/domain/order/controller/OrderController.java
src/main/java/com/example/place/domain/order/dto/CreateOrderRequestDto.java
src/main/java/com/example/place/domain/order/dto/CreateOrderResponseDto.java
src/main/java/com/example/place/domain/order/entity/Order.java
src/main/java/com/example/place/domain/order/entity/OrderStatus.java
src/main/java/com/example/place/domain/order/repository/OrderRepository.java
src/main/java/com/example/place/domain/order/service/OrderService.java
src/main/java/com/example/place/domain/user/repository/UserRepository.java
src/main/java/com/example/place/domain/user/service/UserService.java

- OrderStatus 상태값 추가
- Item 엔티티 주문시 재고 감소 & 재고 증가추가
- order 서비스에서 수량 유무 검증
- 주문 저장
- 주문이 완료되었으므로 재고 차감
- [O] 기능 A 구현
- 관련 이슈: #123
- 참고 자료: [링크]
---

feat: 오더 생성 기능 추가 - OrderStatus 상태값 추가 - Item 엔티티 주문시 재고 감소 & 재고 증가추가 - order 서비스에서 수량 유무 검증 - 주문 저장 - 주문이 완료되었으므로 재고 차감

---

src/main/java/com/example/place/domain/item/controller/ItemController.java
src/main/java/com/example/place/domain/item/dto/request/CreateItemRequest.java
src/main/java/com/example/place/domain/item/dto/response/CreateItemResponse.java
src/main/java/com/example/place/domain/item/entity/Item.java
src/main/java/com/example/place/domain/item/repository/ItemRepository.java
src/main/java/com/example/place/domain/item/service/ItemService.java
src/main/java/com/example/place/domain/itemtag/entity/ItemTag.java
src/main/java/com/example/place/domain/itemtag/repository/ItemTagRepository.java
src/main/java/com/example/place/domain/order/dto/CreateOrderResponseDto.java
src/main/java/com/example/place/domain/tag/entity/Tag.java
src/main/java/com/example/place/domain/tag/repository/TagRepository.java
src/main/java/com/example/place/domain/user/repository/UserRepository.java
src/main/java/com/example/place/domain/usertag/entity/UserTag.java
src/main/java/com/example/place/domain/usertag/repository/UserTagRepository.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

item, tag 기본 erd에 맞춘 수정본

---

src/main/java/com/example/place/domain/user/controller/UserController.java
src/main/java/com/example/place/domain/user/dto/UserResponse.java
src/main/java/com/example/place/domain/user/service/UserService.java

유저 단건 조회기능 추가
- 관련 이슈: #41 
---

feat : 유저 단건 조회기능 추가

---

src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/order/controller/OrderController.java
src/main/java/com/example/place/domain/order/dto/SearchOrderResponseDto.java
src/main/java/com/example/place/domain/order/repository/OrderRepository.java
src/main/java/com/example/place/domain/order/service/OrderService.java

FEATURE: 오더 다건조회 생성 - 본인의 것만 조회가능

---

src/main/java/com/example/place/domain/order/controller/OrderController.java
src/main/java/com/example/place/domain/order/entity/OrderStatus.java
src/main/java/com/example/place/domain/order/service/OrderService.java

- 주문자와 동일한지 검증 
- 주문 상태가 READY 인지 검증 
- 주문상태 변경 READY -> COMPLETED
- [O] 기능 A 구현

[FEATURE] 거래 상태 COMPLETED 변환 api 구현 - 주문자와 동일한지 검증 - 주문 상태가 READY 인지 검증 - 주문상태 변경 READY -> COMPLETED

---

src/main/java/com/example/place/domain/user/controller/UserController.java
src/main/java/com/example/place/domain/user/dto/UserDeleteRequest.java
src/main/java/com/example/place/domain/user/dto/UserPasswordRequest.java
src/main/java/com/example/place/domain/user/dto/UserUpdateRequest.java
src/main/java/com/example/place/domain/user/entity/User.java
src/main/java/com/example/place/domain/user/service/UserService.java

- 유저 자신 정보 수정
- 유저 자신 패스워드 수정
- 회원 삭제
- 관련 이슈: #50 
---

feat : 유저 정보, 비밀번호 수정 및 회원 삭제기능 추가

---

src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/order/controller/OrderController.java
src/main/java/com/example/place/domain/order/service/OrderService.java

거래 취소 상태값 변경 및 수량 증가 API
- 주문자, 또는 admin 인지 아닌지 검증
- ORDERED 상태 일경우만 취소가능 검증
- 취소로 인하여 감소한 만큼 수량 증가
- [O] 기능 A 구현

[FEATURE] 거래 취소 상태값 변경 및 수량 증가 API - 주문자, 또는 admin 인지 아닌지 검증 - ORDERED 상태 일경우만 취소가능 검증 - 취소로 인하여 감소한 만큼 수량 증가

---

src/main/java/com/example/place/domain/order/entity/OrderStatus.java
src/main/java/com/example/place/domain/order/service/OrderService.java

주문 상태 전이 검증 메서드명 명확하게 수정
- [O] 기능 B 리팩토링

refactor: 주문 상태 검증 메서드명 수정

---

src/test/java/com/example/place/domain/Image/service/ImageServiceTest.java

ImageService 관련 테스트 코드를 작성합니다.
아래의 경우에 대한 테스트 코드를 작성
- 이미지 저장 성공
- 이미지 수정 (이미지 삭제) 성공
- 이미지 수정 (이미지 삭제) 성공
- 이미지 수정 (대표 이미지 변경) 성공
- 이미지 삭제 성공
- 대표이미지가 음수인 경우 기본값 변경 성공
- 대표이미지가 범위초과인 경우 기본값 변경 성공
-
로직 흐름 자연스러운지 확인 부탁드립니다.
- 관련 이슈: #86 
- 참고 자료: [링크]
---

feat: ImageService 테스트코드 작성

---

src/main/java/com/example/place/domain/item/entity/Item.java
src/main/java/com/example/place/domain/item/service/ItemService.java
src/main/java/com/example/place/domain/order/dto/CreateOrderRequestDto.java
src/main/java/com/example/place/domain/order/dto/CreateOrderResponseDto.java
src/main/java/com/example/place/domain/order/dto/SearchOrderResponseDto.java
src/main/java/com/example/place/domain/order/dto/UpdateOrderStatusResponseDto.java
src/main/java/com/example/place/domain/order/entity/Order.java
src/test/java/com/example/place/domain/order/service/OrderServiceTest.java

- quantity 가 int형이어서 모두 통일
- [O] 테스트 코드 작성

feature: 주문 성공 테스트 코드 작성

---

src/test/java/com/example/place/domain/order/service/OrderServiceTest.java

testcode 재고 부족 실패
- [O] 테스트 코드 작성

issue/104-feature- creatOrder testcode 재고 부족 실패

---

src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/postcomment/controller/PostCommentController.java
src/main/java/com/example/place/domain/postcomment/entity/PostComment.java
src/main/java/com/example/place/domain/postcomment/repository/PostCommentRepository.java
src/main/java/com/example/place/domain/postcomment/service/PostCommnetService.java

PR 내용 간단 요약살까말까 댓글 전체 조회
- [O] 기능 A 구현

feature: 살까말까 댓글 전체 조회

---

src/main/java/com/example/place/domain/itemcomment/controller/ItemCommentController.java
src/main/java/com/example/place/domain/itemcomment/repository/ItemCommentRepository.java
src/main/java/com/example/place/domain/itemcomment/service/ItemCommentService.java

- 상품의 댓글을 조회합니다
- 상품의 댓글 조회 기능
- 단, 특정 상품에 대해서만 조회가능
- 페이지네이션 처리
로직 흐름 자연스러운지 확인 부탁드립니다.
- 관련 이슈: #67
- 참고 자료: [링크]
---

feat: 상품 댓글 조회

---

src/main/java/com/example/place/domain/user/controller/UserController.java
src/main/java/com/example/place/domain/user/service/UserService.java

어드민 가입 기능 추가
- 관련 이슈: #101
---

feat : 어드민 가입 기능 추가

---

src/main/java/com/example/place/domain/postcomment/controller/PostCommentController.java
src/main/java/com/example/place/domain/postcomment/service/PostCommnetService.java

url경로 수정 및 post 유무 검증
- [O] 기능 B 리팩토링

refactor : url경로 수정 및 post 유무 검증

---

src/main/java/com/example/place/common/dto/PageResponseDto.java

페이지네이션 공통 응답값 반환
- [O] 기능 A 구현

feature : 페이지네이션 공통 응답값 반환

---

src/main/java/com/example/place/domain/postcomment/controller/PostCommentController.java
src/main/java/com/example/place/domain/postcomment/repository/PostCommentRepository.java
src/main/java/com/example/place/domain/postcomment/service/PostCommnetService.java

PageResponseDto 적용 및 N+1 해결
- [O] 기능 B 리팩토링

refactor : PageResponseDto 적용 및 N+1 해결

---

src/main/java/com/example/place/domain/postcomment/controller/PostCommentController.java
src/main/java/com/example/place/domain/postcomment/dto/PostCommentResponse.java
src/main/java/com/example/place/domain/postcomment/service/PostCommnetService.java

- 생성자 접근 제어자 public → private으로 변경
- from 정적 팩토리 메서드 추가
- [O] 기능 B 리팩토링

refactor: PostComment 정적 팩토리 메서드 from() 추가

---

src/main/java/com/example/place/domain/itemcomment/service/ItemCommentService.java
src/main/java/com/example/place/domain/order/repository/OrderRepository.java
src/main/java/com/example/place/domain/order/service/OrderService.java

fix: 병합하며 누락 된 부분 추가

---

src/main/java/com/example/place/domain/itemcomment/service/ItemCommentService.java
src/main/resources/application.yml

상품 댓글 조회 시 해당 상품이 존재하는지 조회하는 로직 추가
- 상품 댓글 조회 시 해당 상품이 존재하는지 조회하는 로직 추가
- 관련 이슈: #157 
- 참고 자료: [링크]
---

feat: 상품 댓글 조회 시 해당 상품이 존재하는지 조회하는 로직 추가

---

src/main/java/com/example/place/domain/user/controller/UserController.java

UserController 엔드포인트 수정
- 관련 이슈: #179
---

refactor : UserController 엔드포인트 수정

---

src/main/java/com/example/place/common/config/SecurityConfig.java
src/main/java/com/example/place/common/filter/JwtFilter.java
src/main/java/com/example/place/common/security/jwt/CustomPrincipal.java

권한 관련 설정 및 시스템 도입 
- jwt필터 시큐리티 config customPrincipal 권환 관련 사항 추가,url 상세 설정 도입
---

Issue/169 feature security config , 권한 사항 시스템 도입

---

src/main/java/com/example/place/common/config/SecurityConfig.java
src/main/java/com/example/place/common/filter/JwtFilter.java

순환 참조 임시 해결

---

src/main/java/com/example/place/domain/post/controller/PostController.java
src/main/java/com/example/place/domain/post/service/PostService.java

내 글 조회 메서드 findMyPost를 getMyPost으로 이름 변경 했습니다.
- 관련 이슈: #123
- 참고 자료: [링크]
---

Refactor(post): findMyPost>getMyPost으로 수정

---

src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/order/repository/OrderRepository.java
src/main/java/com/example/place/domain/order/service/OrderService.java

해당 상품의 진행 중인 주문이 있다면 삭제 못하도록 예외처리
- 해당 상품의 진행 중인 주문이 있다면 삭제 못하도록 예외처리
- 관련 이슈: #202 
- 참고 자료: [링크]
---

feat: 해당 상품의 진행 중인 주문이 있다면 삭제 못하도록 예외처리

---

src/main/java/com/example/place/common/config/SecurityConfig.java
src/main/java/com/example/place/common/filter/JwtFilter.java
src/main/java/com/example/place/domain/user/service/CustomUserDetailsService.java

CustomUserDetailsService 구현 , Security Config, jwt filter에서 User 도메인의 Repository에 직접 의존하지 않고 
CustomUserDetailsService 를 통해 유저 정보를 조회하도록 구성
customuserdetailservice 구현
---

Issue/186 feature customuserdetailservice 구현

---

src/main/java/com/example/place/common/config/CustomAuthenticationEntryPoint.java
src/main/java/com/example/place/common/exception/enums/ExceptionCode.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

hotfix: 안쓰는 ExceptionCode 제거 및 CustomAuthenticationEntryPoint 응답 메세지 변경

---

src/main/java/com/example/place/domain/item/entity/Item.java
src/main/java/com/example/place/domain/item/service/ItemService.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

sprint로 잘못 보내 develop으로 다시보냅니다

---

src/main/java/com/example/place/domain/itemcomment/controller/ItemCommentController.java
src/main/java/com/example/place/domain/order/controller/OrderController.java
src/main/java/com/example/place/domain/postcomment/controller/PostCommentController.java
src/main/java/com/example/place/domain/vote/service/VoteService.java

단수인 주소지 변경, 주소지의 my -> me 변경과 서비스 파라매터에 있는 @Valid를 제거하였습니다.
---

hotfix: api mapping url 일부 변경

---

src/main/java/com/example/place/domain/item/controller/ItemController.java
src/main/java/com/example/place/domain/item/repository/ItemRepository.java
src/main/java/com/example/place/domain/item/service/ItemService.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

상품검색조건에 itemDescription추가

---

src/main/java/com/example/place/domain/item/controller/ItemController.java
src/main/java/com/example/place/domain/item/dto/request/ItemRequest.java
src/main/java/com/example/place/domain/item/dto/response/ItemResponse.java
src/main/java/com/example/place/domain/item/repository/ItemRepository.java
src/main/java/com/example/place/domain/item/service/ItemService.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

sprint의 메서드 develop으로 최신화했습니다

---

src/main/java/com/example/place/domain/item/repository/ItemRepository.java
src/main/java/com/example/place/domain/item/service/ItemService.java
src/main/java/com/example/place/domain/itemcomment/repository/ItemCommentRepository.java
src/main/java/com/example/place/domain/itemcomment/service/ItemCommentService.java
src/main/java/com/example/place/domain/order/service/OrderService.java
src/main/resources/application.yml

feat: 상품, 상품 댓글 소프트 딜리트 검증 로직
- 상품 조회 시 검증 
- 상품 수정 시 검증
- 상품 삭제 시 검증
- 상품 댓글 조회 시 검증
- 상품 댓글 수정 시 검증
- 상품 댓글 삭제 시 검증
- 관련 이슈: #231
- 참고 자료: [링크]
---

feat: 상품, 상품 댓글 소프트 딜리트 삭제 로직

---

src/main/java/com/example/place/domain/post/service/PostDeleteService.java

Develop 변경사항 병합
- Develop 변경사항 병합

Develop 변경사항 병합

---

src/main/java/com/example/place/domain/item/dto/request/ItemRequest.java
src/main/java/com/example/place/domain/item/dto/response/ItemResponse.java
src/main/java/com/example/place/domain/item/entity/Item.java
src/main/java/com/example/place/domain/item/service/ItemService.java

- userRole이 admin 인 경우 자동적으로 true로 입력
- userRole이 user 인 경우 자동적으로 false 입력
- [O] 기능 A 구현

feature: 상품 생성 한정상품 설정기능 추가 

---

src/main/java/com/example/place/domain/item/entity/Item.java

- count, totalCount 같이 업데이트
- [O] 기능 A 구현

feature: 상품 개수 수정 totalCount 수정시

---

build.gradle
src/main/java/com/example/place/common/config/RedisConfig.java
src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/item/entity/Item.java
src/main/java/com/example/place/domain/item/service/ItemService.java
src/main/java/com/example/place/domain/item/service/StockService.java
src/main/java/com/example/place/domain/order/service/OrderService.java

- 상품이 1개이면서 한정상품이 아닌경우 적용
- [O ] 기능 A 구현

feature: 상품 구매 분산락 

---

src/main/java/com/example/place/common/exception/enums/ExceptionCode.java
src/main/java/com/example/place/domain/item/controller/ItemController.java
src/main/java/com/example/place/domain/item/repository/ItemRepository.java
src/main/java/com/example/place/domain/item/repository/ItemRepositoryCustom.java
src/main/java/com/example/place/domain/item/repository/ItemRepositoryCustomImpl.java
src/main/java/com/example/place/domain/item/service/ItemService.java

Query DSL을 적용하여 상품을 서치하도록 합니다.
- 키워드(제목과 설명 중), 태그, 유저Id로 상품을 서치할 수 있게합니다.
- QueryDSL을 도입하였습니다.
- N+1문제를 해결하며 페이지네이션이 적용되도록 합니다.
- 관련 이슈: #259 
- 참고 자료: [링크]
---

feat: 상품 서치 구현

---

src/main/java/com/example/place/domain/Image/repository/ImageRepository.java
src/main/java/com/example/place/domain/Image/service/ImageService.java
src/main/java/com/example/place/domain/post/controller/PostController.java
src/main/java/com/example/place/domain/post/dto/response/PostGetAllResponseDto.java
src/main/java/com/example/place/domain/post/dto/response/PostResponseDto.java
src/main/java/com/example/place/domain/post/dto/response/PostSearchAllResponseDto.java
src/main/java/com/example/place/domain/post/repository/PostRepository.java
src/main/java/com/example/place/domain/post/service/PostReadService.java
src/main/java/com/example/place/domain/post/service/PostService.java
src/main/java/com/example/place/domain/vote/service/VoteService.java

투표 결과를 포함한 내 게시물 전체 조회 구현하였습니다. 
기존 게시물 전체 조회 리팩토링 하였습니다.
- 투표 결과를 포함한 내 게시물 전체 조회 구현
- get MainImagesForPosts(), getVotesForPosts() 구조 통일 및 정리
- 전체 조회 공동 로직 별도의 메서드로 분리
- 관련 이슈: #260
- 참고 자료: [링크]
---

feat: 투표 결과를 포함한 내 게시물 전체 조회 구현 + 기존 게시물 전체 조회 리팩토링

---

src/main/java/com/example/place/domain/item/service/StockService.java

- 어떤식으로 락을 나누는게 아닌 분산락 적용
- [O] 기능 A 구현

feature : 분산락 적용

---

src/main/java/com/example/place/domain/newsfeedcomment/controller/NewsfeedCommentController.java
src/main/java/com/example/place/domain/newsfeedcomment/entity/NewsfeedComment.java
src/main/java/com/example/place/domain/newsfeedcomment/service/NewsfeedCommentService.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

feature(newsfeedcomment): 댓글 수정 기능 구현

---

build.gradle
src/main/java/com/example/place/common/config/CacheConfig.java
src/main/java/com/example/place/common/dto/PageResponseDto.java
src/main/java/com/example/place/domain/newsfeed/service/NewsfeedService.java

뉴스피드 도메인에 캐싱을 적용합니다
- 리스트 캐싱 10분
- 단건 캐싱 1시간
- 관련 이슈: #311, #313, #328 
- 참고 자료: [링크]
---

feat: 뉴스피드 캐싱 적용

---

src/main/java/com/example/place/common/config/CacheConfig.java

PR 내용 간단 요약
- 관련 이슈: #123
- 참고 자료: [링크]
---

refactor : Keys -> Scan 사용하도록 수정

---

src/test/java/com/example/place/domain/mail/service/MailRequestServiceTest.java
src/test/java/com/example/place/domain/mail/service/MailSendServiceTest.java
src/test/java/com/example/place/domain/mail/service/RedisMailQueueServiceTest.java

이메일 서비스 테스트
- 관련 이슈: #342
- 참고 자료: [링크]
---

test: 이메일 서비스 테스트

---

src/test/java/com/example/place/domain/order/service/OrderServiceTest.java
src/test/java/com/example/place/domain/user/service/UserServiceTest.java
src/test/java/com/example/place/domain/vote/service/VoteServiceTest.java

회원 서비스 테스트 코드
- 관련 이슈: #342
- 참고 자료: [링크]
---

test: 회원 서비스 테스트 코드

---

src/test/java/com/example/place/domain/newsfeed/service/NewsfeedServiceTest.java

test:새소식 서비스 테스트 코드
- 관련 이슈: #342 
- 참고 자료: [링크]
---

test:새소식 서비스 테스트 코드
